# Generated by Django 2.0.5 on 2018-09-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180906_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='bane.png', null=True, upload_to=''),
        ),
    ]
