# Generated by Django 2.0.5 on 2018-09-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180907_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
