# Generated by Django 2.0.5 on 2018-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20180907_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
